#pool.initialSize=1
#pool.minIdle=1
#pool.maxActive=5
#pool.maxWait=10000

server:
  port: 8081
  session-timeout: 30  
#数据库连接配置
Mysql:
spring.datasource:
  url: jdbc:mysql://192.168.1.62:3306/liu?useUnicode=true&characterEncoding=utf-8&useSSL=true
  username: root
  password: 123456
  driver-class-name: com.mysql.jdbc.Driver
  max-active: 50  
  max-idle: 6  
  min-idle: 2  
  initial-size: 6  

mybatis.type-aliases-package: com.entity
#第一次加载hibernate时根据model类会自动建立起表的结构（前提是先建立好数据库），以后加载hibernate时根据model类自动更新表结构，即使表结构改变了但表中的行仍然存在不会删除以前的行。
spring.jpa:
  hibernate.ddl-auto: update
  show-sql: true
#默认支持文件上传.
spring.http.multipart.enabled: true
spring.http.multipart:
 # 最大支持文件大小
  max-file-size: 2Mb
 # 最大支持请求大小
  max-request-size: 10Mb

